pages = [{"l":"index.html","n":"library-example","t":"library-example","d":""},
{"l":"docs/getting-started.html","n":"Getting started","t":"Getting started","d":""},
{"l":"docs/reference.html","n":"Reference","t":"Reference","d":""},
{"l":"blog/index.html","n":"Blog","t":"Blog","d":""},
{"l":"blog/2021/06/30/first-post.html","n":"First post","t":"First post","d":""},
{"l":"docs/Contributing/index.html","n":"Contributing","t":"Contributing","d":""},
{"l":"docs/contributing/setup.html","n":"Setup","t":"Setup","d":""},
{"l":"docs/contributing/releasing.html","n":"Realeasing","t":"Realeasing","d":""},
{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/ch/epfl/scala.html","n":"ch.epfl.scala","t":"package ch.epfl.scala","d":"ch/epfl/scala"},
{"l":"api/ch/epfl/scala/Example$.html","n":"Example","t":"object Example","d":"ch/epfl/scala/Example$"},
{"l":"api/ch/epfl/scala/Example$.html","n":"doNothing","t":"def doNothing[A](a: A): A","d":"ch/epfl/scala/Example$"},
{"l":"docs/index.html","n":"library-example","t":"library-example","d":""}];