pages = [{"l":"index.html","n":"library-example","t":"library-example","d":""},
{"l":"docs/getting-started.html","n":"getting-started","t":"getting-started","d":""},
{"l":"docs/contributing.html","n":"contributing","t":"contributing","d":""},
{"l":"index.html","n":"index","t":"index","d":""},
{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/ch/epfl/scala.html","n":"ch.epfl.scala","t":"package ch.epfl.scala","d":"ch/epfl/scala"},
{"l":"api/ch/epfl/scala/Example$.html","n":"Example","t":"object Example","d":"ch/epfl/scala/Example$"},
{"l":"api/ch/epfl/scala/Example$.html","n":"doNothing","t":"def doNothing[A](a: A): A","d":"ch/epfl/scala/Example$"},
{"l":"docs/reference.html","n":"reference","t":"reference","d":""},
{"l":"docs/index.html","n":"library-example","t":"library-example","d":""}];