name: Continuous integration
on: [push]

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Documentation
        run: |
          mkdir site-output
          sbt doc
