name: Continuous publication
on:
  push:
    branches: ['**']
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags, required for sbt-dynver
      - uses: olafurpg/setup-scala@v10
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  publishSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - name: Generate site
        run: sbt doc
      - name: Deploy new site
        run: |
          git config user.name "gaction"
          git config user.email "gaction@github.com"
          git remote set-url origin https://gaction:${GITHUB_TOKEN}@github.com/vincenzobaz/library-example.git
          git checkout gh-pages
          tag="$(basename ${{ github.ref }})"
          mv target/site-output versions/$tag
          git add versions/$tag
          git commit -m "[action] adding versions $tag"
          touch sites.json
          cat sites.json | jq --arg newver $tag '.versions[$newver] = "https://vincenzobaz.github.io/library-example/versions\($newver)"' > sites.json
          git add sites.json
          git commit sites.json -m "[action] add new version sites.json"
          git push origin gh-pages
